# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
      image: mongo
      environment:
        - MONGO_INITDB_DATABASE=describe
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=pass
      ports:
        - "27017:27017"
      volumes:
        - mongo_db:/data/db


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/

volumes:
  mongo_db:
    external: true
